modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/teamauroramods/BayouBlues/issues"
license = "GPLv3"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "Team Aurora"
description = "A mod focused on adding biomes with realism and the core Minecraft experience in mind."
displayURL = "https://discord.gg/VzXSCFp"
logoFile = "logo.png"


[[dependencies.${id}]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "pollen"
mandatory = true
versionRange = "[1.4.9,)"
ordering = "BEFORE"
side = "BOTH"